package GUI;

import java.awt.BorderLayout;

import javax.swing.JPanel;
import java.awt.Dimension;
import javax.swing.JLabel;
import javax.swing.JComboBox;
import javax.swing.JTextPane;
import java.awt.GridBagLayout;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import javax.swing.BoxLayout;
import javax.swing.SwingConstants;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.ListSelectionModel;

public class ChessBoardMain extends javax.swing.JFrame {
	public static final long serialVersionUID = 0;
	public ChessBoardPanel boardPanel;
	public final JTextPane notation_text = new JTextPane();
	public final JComboBox<String> port_combo;
	public final JButton copy_button;
	private JTable table;
	
	/** Creates new form SVGIconDemo */
	public ChessBoardMain() {
		setTitle("Chess Board");
		setMinimumSize(new Dimension(400, 300));
		initComponents();
		 
		boardPanel = new ChessBoardPanel();
		boardPanel.setPreferredSize(new Dimension(400, 400));
	
		this.getContentPane().add(boardPanel, BorderLayout.CENTER);
		boardPanel.setLayout(new BorderLayout(0, 0));
		
		JPanel status_panel = new JPanel();
		status_panel.setPreferredSize(new Dimension(this.getWidth(), 25));
		getContentPane().add(status_panel, BorderLayout.SOUTH);
		status_panel.setLayout(new BoxLayout(status_panel, BoxLayout.X_AXIS));
		
		JLabel status_label = new JLabel("Status:");
		status_panel.add(status_label);

		
		JPanel tool_panel = new JPanel();
		tool_panel.setPreferredSize(new Dimension(210, 10));
		getContentPane().add(tool_panel, BorderLayout.EAST);
		GridBagLayout gbl_tool_panel = new GridBagLayout();
		gbl_tool_panel.columnWidths = new int[] {5, 100, 100};
		gbl_tool_panel.rowHeights = new int[] {25, 0, 30};
		gbl_tool_panel.columnWeights = new double[]{1.0, 1.0, 0.0};
		gbl_tool_panel.rowWeights = new double[]{0.0, 1.0, 0.0};
		tool_panel.setLayout(gbl_tool_panel);
		
		JLabel port_label = new JLabel("Select Port:");
		port_label.setHorizontalAlignment(SwingConstants.CENTER);
		GridBagConstraints gbc_port_label = new GridBagConstraints();
		gbc_port_label.insets = new Insets(0, 0, 5, 5);
		gbc_port_label.gridx = 1;
		gbc_port_label.gridy = 0;
		gbc_port_label.fill = GridBagConstraints.BOTH;
		tool_panel.add(port_label, gbc_port_label);
		
		port_combo = new JComboBox<String>();
		port_combo.setPreferredSize(new Dimension(80, 23));
		GridBagConstraints gbc_port_combo = new GridBagConstraints();
		gbc_port_combo.fill = GridBagConstraints.BOTH;
		gbc_port_combo.ipadx = 5;
		gbc_port_combo.ipady = 5;
		gbc_port_combo.insets = new Insets(0, 0, 5, 5);
		gbc_port_combo.gridx = 2;
		gbc_port_combo.gridy = 0;
		tool_panel.add(port_combo, gbc_port_combo);
		
		JPanel notation_panel = new JPanel();
		GridBagConstraints gbc_notation_panel = new GridBagConstraints();
		gbc_notation_panel.gridwidth = 2;
		gbc_notation_panel.insets = new Insets(0, 0, 5, 5);
		gbc_notation_panel.fill = GridBagConstraints.BOTH;
		gbc_notation_panel.gridx = 1;
		gbc_notation_panel.gridy = 1;
		tool_panel.add(notation_panel, gbc_notation_panel);
		notation_panel.setLayout(new BorderLayout(0, 0));
		
		JLabel notation_label = new JLabel("Notation:");
		notation_label.setLabelFor(notation_text);
		notation_label.setHorizontalAlignment(SwingConstants.CENTER);
		notation_panel.add(notation_label, BorderLayout.NORTH);
		notation_text.setEditable(false);
		notation_panel.add(notation_text, BorderLayout.CENTER);
		
		table = new JTable();
		table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		table.setModel(new DefaultTableModel(
			new Object[][] {
			},
			new String[] {
				"Moves", "N"
			}
		));
		table.setShowHorizontalLines(false);
		table.setShowGrid(false);
		table.setRowSelectionAllowed(false);
		notation_panel.add(table, BorderLayout.SOUTH);
		
		copy_button = new JButton("Copy");
		GridBagConstraints gbc_copy_button = new GridBagConstraints();
		gbc_copy_button.insets = new Insets(0, 0, 5, 5);
		gbc_copy_button.fill = GridBagConstraints.BOTH;
		gbc_copy_button.gridx = 2;
		gbc_copy_button.gridy = 2;
		tool_panel.add(copy_button, gbc_copy_button);
		pack();
	}

	/**
	 * This method is called from within the constructor to * initialize the
	 * form. * WARNING: Do NOT modify this code. The content of this method is *
	 * always regenerated by the Form Editor.
	 */
	private void initComponents() {
		getContentPane().setLayout(new java.awt.BorderLayout());
	}


}